import { Inter } from 'next/font/google'
import './globals.css'
import { UiProvider } from "../../contexts/UiContext";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Green Harbour',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <UiProvider>

    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </UiProvider>
  )
}
