import { Inter } from 'next/font/google'
import './globals.css'
import { UiProvider } from "../../contexts/UiContext";
import Navbar from '../../components/LandingPage/Navbar';
import Footer from '../../components/LandingPage/Footer';
import NextTopLoader from 'nextjs-toploader';
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Green Harbour',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <UiProvider>

    <html lang="en">
      <body className={inter.className}>
        <Toaster/>
        <NextTopLoader color='#EA580C' />
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
    </UiProvider>
  )
}
